# Generated by Django 5.2.12 on 2026-03-03 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycles', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectiveScoringPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('normalization_method', models.CharField(default='CAPPED_LINEAR_V1', max_length=32)),
                ('pd_weight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('plans_weight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('pd_target_hours', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pd_max_hours', models.DecimalField(decimal_places=2, max_digits=7)),
                ('plans_target_count', models.PositiveIntegerField()),
                ('plans_max_count', models.PositiveIntegerField()),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['is_active', 'effective_from'], name='objective_s_is_acti_6c6f06_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('pd_weight__gte', 0), ('pd_weight__lte', 1)), name='ck_pd_weight_range'), models.CheckConstraint(condition=models.Q(('plans_weight__gte', 0), ('plans_weight__lte', 1)), name='ck_plans_weight_range'), models.CheckConstraint(condition=models.Q(('pd_max_hours__gt', models.F('pd_target_hours'))), name='ck_pd_cap_gt_target'), models.CheckConstraint(condition=models.Q(('plans_max_count__gt', models.F('plans_target_count'))), name='ck_plans_cap_gt_target')],
            },
        ),
        migrations.CreateModel(
            name='ObjectiveScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('breakdown_json', models.JSONField(default=dict)),
                ('policy_version', models.CharField(max_length=20)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objective_scores', to='cycles.evaluationcycle')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objective_scores', to='teachers.teacher')),
            ],
            options={
                'indexes': [models.Index(fields=['cycle', 'policy_version'], name='objective_s_cycle_i_2fb0f0_idx')],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'cycle'), name='uq_objective_teacher_cycle'), models.CheckConstraint(condition=models.Q(('objective_total__gte', 0), ('objective_total__lte', 100)), name='ck_objective_total_0_100')],
            },
        ),
    ]
