# Generated by Django 5.2.12 on 2026-03-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objective_scoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='objectivescoringpolicy',
            name='ck_plans_weight_range',
        ),
        migrations.RemoveConstraint(
            model_name='objectivescoringpolicy',
            name='ck_plans_cap_gt_target',
        ),
        migrations.RenameField(
            model_name='objectivescoringpolicy',
            old_name='plans_weight',
            new_name='training_weight',
        ),
        migrations.RemoveField(
            model_name='objectivescoringpolicy',
            name='plans_max_count',
        ),
        migrations.RemoveField(
            model_name='objectivescoringpolicy',
            name='plans_target_count',
        ),
        migrations.AddField(
            model_name='objectivescoringpolicy',
            name='training_max_hours',
            field=models.DecimalField(decimal_places=2, default=150, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objectivescoringpolicy',
            name='training_target_hours',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='objectivescoringpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('training_weight__gte', 0), ('training_weight__lte', 1)), name='ck_training_weight_range'),
        ),
        migrations.AddConstraint(
            model_name='objectivescoringpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('training_max_hours__gt', models.F('training_target_hours'))), name='ck_training_cap_gt_target'),
        ),
    ]
