# Generated by Django 5.2.12 on 2026-03-03 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycles', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherMetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pd_hours', models.DecimalField(decimal_places=2, max_digits=7)),
                ('plans_count', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metric_snapshots_created', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_snapshots', to='cycles.evaluationcycle')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_snapshots', to='teachers.teacher')),
            ],
            options={
                'indexes': [models.Index(fields=['teacher', 'cycle'], name='metrics_tea_teacher_99075d_idx'), models.Index(fields=['cycle', 'created_at'], name='metrics_tea_cycle_i_7f3bb4_idx')],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'cycle'), name='uq_metric_teacher_cycle'), models.CheckConstraint(condition=models.Q(('pd_hours__gte', 0)), name='ck_pd_hours_non_negative'), models.CheckConstraint(condition=models.Q(('plans_count__gte', 0)), name='ck_plans_count_non_negative')],
            },
        ),
    ]
