# Generated by Django 5.2.12 on 2026-03-05 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0001_initial'),
        ('metrics', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teachermetricsnapshot',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved')], default='PENDING', max_length=16),
        ),
        migrations.AddField(
            model_name='teachermetricsnapshot',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teachermetricsnapshot',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metric_snapshots_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='teachermetricsnapshot',
            index=models.Index(fields=['approval_status', 'cycle'], name='metrics_tea_approva_07bd72_idx'),
        ),
    ]
