# Generated by Django 5.2.12 on 2026-03-05 23:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0001_initial'),
        ('metrics', '0002_teachermetricsnapshot_approval_status_and_more'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teachermetricsnapshot',
            name='ck_plans_count_non_negative',
        ),
        migrations.RemoveField(
            model_name='teachermetricsnapshot',
            name='plans_count',
        ),
        migrations.AddField(
            model_name='teachermetricsnapshot',
            name='training_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='teachermetricsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('training_hours__gte', 0)), name='ck_training_hours_non_negative'),
        ),
    ]
