# Generated by Django 5.2.12 on 2026-03-05 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycles', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(choices=[('xgboost', 'XGBoost'), ('random_forest', 'Random Forest')], max_length=32)),
                ('version', models.CharField(max_length=32, unique=True)),
                ('model_path', models.CharField(help_text='Relative path to the .joblib file inside ml_models/', max_length=255)),
                ('metrics_json', models.JSONField(default=dict, help_text='Training metrics: MAE, R², RMSE, etc.')),
                ('feature_names', models.JSONField(default=list, help_text='Ordered list of feature names used during training')),
                ('is_active', models.BooleanField(default=False)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('sample_count', models.PositiveIntegerField(default=0, help_text='Number of training samples used')),
            ],
            options={
                'ordering': ['-trained_at'],
                'indexes': [models.Index(fields=['is_active', 'algorithm'], name='ml_scoring__is_acti_7b5de8_idx')],
            },
        ),
        migrations.CreateModel(
            name='MLPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ml_expected_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('features_json', models.JSONField(default=dict, help_text='Feature values used for this prediction')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_predictions', to='cycles.evaluationcycle')),
                ('model_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='ml_scoring.mlmodelrecord')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_predictions', to='teachers.teacher')),
            ],
            options={
                'indexes': [models.Index(fields=['cycle', 'computed_at'], name='ml_scoring__cycle_i_af4ca4_idx')],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'cycle'), name='uq_ml_prediction_teacher_cycle'), models.CheckConstraint(condition=models.Q(('ml_expected_score__gte', 0), ('ml_expected_score__lte', 100)), name='ck_ml_expected_score_0_100')],
            },
        ),
    ]
