# Generated by Django 5.2.12 on 2026-03-03 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('weight_percent', models.PositiveSmallIntegerField()),
                ('order', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='criteria_ev_is_acti_304e9f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('weight_percent__in', [5, 10])), name='ck_criterion_weight_5_or_10')],
            },
        ),
    ]
