# Generated by Django 5.2.12 on 2026-03-03 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='schools.school')),
            ],
            options={
                'indexes': [models.Index(fields=['school', 'is_active'], name='cycles_eval_school__67ca84_idx')],
                'constraints': [models.UniqueConstraint(fields=('school', 'name'), name='uq_cycle_school_name'), models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='ck_cycle_dates_order')],
            },
        ),
    ]
