# Generated by Django 5.2.12 on 2026-03-03 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comparisons', '0001_initial'),
        ('cycles', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_REVIEW', 'In Review'), ('CLOSED', 'Closed')], default='OPEN', max_length=16)),
                ('decision_note', models.TextField(blank=True, default='')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases_closed', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='cycles.evaluationcycle')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases_opened', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='teachers.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('REVIEW', 'Review'), ('HIGH_RISK', 'High Risk')], max_length=16)),
                ('code', models.CharField(max_length=64)),
                ('message', models.TextField()),
                ('payload_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flags', to='flags_cases.case')),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='comparisons.comparisonresult')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='cycles.evaluationcycle')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='teachers.teacher')),
            ],
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status', 'opened_at'], name='flags_cases_status_163bdc_idx'),
        ),
        migrations.AddIndex(
            model_name='flag',
            index=models.Index(fields=['severity', 'created_at'], name='flags_cases_severit_955074_idx'),
        ),
        migrations.AddIndex(
            model_name='flag',
            index=models.Index(fields=['teacher', 'cycle'], name='flags_cases_teacher_9562d7_idx'),
        ),
    ]
