# Generated by Django 5.2.12 on 2026-03-03 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycles', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('objective_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('deviation', models.DecimalField(decimal_places=2, max_digits=6)),
                ('deviation_level', models.CharField(choices=[('NORMAL', 'Normal'), ('REVIEW', 'Review'), ('HIGH_RISK', 'High Risk')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_results', to='cycles.evaluationcycle')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_results', to='teachers.teacher')),
            ],
            options={
                'indexes': [models.Index(fields=['deviation_level', 'created_at'], name='comparisons_deviati_6a80f2_idx')],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'cycle'), name='uq_cmp_teacher_cycle')],
            },
        ),
    ]
