# Generated by Django 5.2.12 on 2026-03-05 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0002_comparisonresult_ai_deviation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparisonresult',
            name='ai_deviation',
        ),
        migrations.RemoveField(
            model_name='comparisonresult',
            name='ai_expected_score',
        ),
    ]
