# Generated by Django 5.2.12 on 2026-03-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0003_remove_ai_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonresult',
            name='ml_deviation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='comparisonresult',
            name='ml_expected_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
