# Generated by Django 5.2.12 on 2026-03-03 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('criteria', '0001_initial'),
        ('cycles', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINAL', 'Final')], default='DRAFT', max_length=12)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='cycles.evaluationcycle')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manager_evaluations', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='teachers.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='criteria.evaluationcriterion')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='evaluations.managerevaluation')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_total_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rating_level', models.CharField(max_length=32)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('evaluation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='evaluations.managerevaluation')),
            ],
        ),
        migrations.AddIndex(
            model_name='managerevaluation',
            index=models.Index(fields=['cycle', 'status'], name='evaluations_cycle_i_2b61cf_idx'),
        ),
        migrations.AddConstraint(
            model_name='managerevaluation',
            constraint=models.UniqueConstraint(fields=('teacher', 'cycle'), name='uq_eval_teacher_cycle'),
        ),
        migrations.AddConstraint(
            model_name='evaluationitem',
            constraint=models.UniqueConstraint(fields=('evaluation', 'criterion'), name='uq_evalitem_eval_criterion'),
        ),
        migrations.AddConstraint(
            model_name='evaluationitem',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 1), ('score__lte', 5)), name='ck_evalitem_score_1_5'),
        ),
        migrations.AddConstraint(
            model_name='scoresummary',
            constraint=models.CheckConstraint(condition=models.Q(('manager_total_score__gte', 0), ('manager_total_score__lte', 100)), name='ck_manager_total_0_100'),
        ),
    ]
