# Generated by Django 5.2.12 on 2026-03-03 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0001_initial'),
        ('cycles', '0001_initial'),
        ('evaluations', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_text', models.TextField()),
                ('evidence_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidences', to='criteria.evaluationcriterion')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='cycles.evaluationcycle')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_evidences', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='teachers.teacher')),
            ],
            options={
                'indexes': [models.Index(fields=['teacher', 'cycle', 'created_at'], name='evaluations_teacher_c0eff7_idx'), models.Index(fields=['criterion', 'created_at'], name='evaluations_criteri_f12890_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('evidence_text', ''), _negated=True), name='ck_evidence_text_not_empty')],
            },
        ),
    ]
